# -------------------------------------------------------------------------------------
# Menu Configuration
# See: https://fixit.lruihao.cn/documentation/basics/#menu-configuration
# -------------------------------------------------------------------------------------

[[main]]
  identifier = "Home"
  name = "首页"
  url = "/"
  weight = 1
  [main.params]
    icon = "fa-solid fa-house"

[[main]]
  identifier = "posts"
  name = "文章"
  url = "/posts/"
  weight = 2
  [main.params]
    icon = "fa-solid fa-archive"

[[main]]
  identifier = "categories"
  name = "分类"
  url = "/categories/"
  weight = 3
  [main.params]
    icon = "fa-solid fa-folder-tree"

[[main]]
  identifier = "tags"
  name = "标签"
  url = "/tags/"
  weight = 3
  [main.params]
    icon = "fa-solid fa-tags fa-fw fa-sm"

[[main]]
  identifier = "friends"
  name = "友链"
  url = "/friends/"
  weight = 5
  [main.params]
    icon = "fa-solid fa-users-viewfinder fa-fw fa-sm"

[[main]]
  identifier = "about"
  name = "关于"
  url = "/about/"
  weight = 60
  [main.params]
    icon = "fa-regular fa-id-card fa-fw fa-sm"
