# -------------------------------------------------------------------------------------
# Modules Configuration
# See: https://gohugo.io/configuration/module/
# -------------------------------------------------------------------------------------

[[imports]]
path = "github.com/hugo-fixit/FixIt"

[hugoVersion]
extended = true
min = "0.161.0"
